[unix_http_server]
file=/Users/raghavjasthi/Desktop/Fusion-1/supervisor.sock

[supervisord]
logfile=/Users/raghavjasthi/Desktop/Fusion-1/logs/supervisord.log
logfile_maxbytes=10MB
logfile_backups=5
loglevel=info
pidfile=/Users/raghavjasthi/Desktop/Fusion-1/supervisord.pid
nodelay=false
silent=false
minfds=1024
minprocs=200
umask=022
user=raghavjasthi
directory=/Users/raghavjasthi/Desktop/Fusion-1

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///Users/raghavjasthi/Desktop/Fusion-1/supervisor.sock

[include]
files = supervisor_django.conf
