# Generated by Django 6.0.3 on 2026-03-14 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_academic', '0002_userprofile_leave_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='roll_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
