# Generated by Django 6.0.3 on 2026-03-23 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_academic', '0004_academic_calendar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentClearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('semester', models.IntegerField()),
                ('academic_year', models.CharField(max_length=10)),
                ('requested_date', models.DateField(auto_now_add=True)),
                ('processed_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clearances_processed', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clearances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'status'], name='other_acade_student_a28d84_idx'), models.Index(fields=['department', 'status'], name='other_acade_departm_8f8d75_idx')],
                'unique_together': {('student', 'department', 'semester', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='StudentDues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dues_type', models.CharField(choices=[('tuition', 'Tuition Fee'), ('library', 'Library Fine'), ('hostel', 'Hostel Dues'), ('lab', 'Lab Fee'), ('activity', 'Activity Fee'), ('exam', 'Exam Fee'), ('other', 'Other Dues')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial Payment'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('department', models.CharField(max_length=255)),
                ('is_cleared', models.BooleanField(default=False)),
                ('cleared_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('semester', models.IntegerField()),
                ('academic_year', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cleared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dues_cleared', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'status'], name='other_acade_student_343dcf_idx'), models.Index(fields=['department', 'is_cleared'], name='other_acade_departm_a95c3a_idx')],
                'unique_together': {('student', 'dues_type', 'semester', 'academic_year')},
            },
        ),
    ]
