# Generated by Django 6.0.3 on 2026-03-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_academic', '0012_bonafiderequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonafiderequest',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='bonafide_certificates/'),
        ),
        migrations.AddField(
            model_name='bonafiderequest',
            name='certificate_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
