# Generated by Django 5.2.8 on 2026-03-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_academic', '0013_bonafiderequest_certificate_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantshipclaim',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assistantshipclaim',
            name='student_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assistantshipclaim',
            name='student_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assistantshipclaim',
            name='student_withdrawn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assistantshipclaim',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assistantshipclaim',
            name='withdraw_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assistantshipclaim',
            name='withdrawn_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
