# Generated by Django 5.2.8 on 2026-03-26 06:35

from django.db import migrations, models


def seed_assistantship_approvers(apps, schema_editor):
    AssistantshipApprover = apps.get_model("other_academic", "AssistantshipApprover")
    seed_data = [
        ("Dr. HOD CSE", "hod", "CSE", "hod.cse@iiitdmj.ac.in"),
        ("Dr. HOD ECE", "hod", "ECE", "hod.ece@iiitdmj.ac.in"),
        ("Dr. TA Supervisor 1", "ta_supervisor", "CSE", "ta.supervisor1@iiitdmj.ac.in"),
        ("Dr. TA Supervisor 2", "ta_supervisor", "ECE", "ta.supervisor2@iiitdmj.ac.in"),
        ("Dr. Thesis Supervisor 1", "thesis_supervisor", "CSE", "thesis.supervisor1@iiitdmj.ac.in"),
        ("Dr. Thesis Supervisor 2", "thesis_supervisor", "ECE", "thesis.supervisor2@iiitdmj.ac.in"),
    ]
    for name, role, department, email in seed_data:
        AssistantshipApprover.objects.get_or_create(
            name=name,
            role=role,
            defaults={"department": department, "email": email, "is_active": True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('other_academic', '0014_assistantshipclaim_reviewed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantshipApprover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('hod', 'HOD'), ('ta_supervisor', 'TA Supervisor'), ('thesis_supervisor', 'Thesis Supervisor')], max_length=30)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['role', 'name'],
                'unique_together': {('name', 'role')},
            },
        ),
        migrations.RunPython(seed_assistantship_approvers, migrations.RunPython.noop),
    ]
