# Generated by Django 5.2.8 on 2026-03-26 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('other_academic', '0016_alter_branchchangerequest_status_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dropcourserequest',
            unique_together=set(),
        ),
    ]
