# Generated by Django 5.2.8 on 2026-03-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_academic', '0018_userprofile_is_pg_student_seminar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noduesrequest',
            name='clearance_file',
            field=models.FileField(blank=True, null=True, upload_to='no_dues_clearance_files/'),
        ),
        migrations.AddField(
            model_name='noduesrequest',
            name='clearance_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
