# Generated by Django 6.0.3 on 2026-04-21 04:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_academic', '0029_nodues_domain_approvals_and_lab_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='assistantshipclaim',
            index=models.Index(fields=['student', 'created_at'], name='asst_student_created_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantshipclaim',
            index=models.Index(fields=['thesis_status', 'ta_status', 'hod_status', 'acadadmin_status'], name='assistantship_stage_idx'),
        ),
        migrations.AddIndex(
            model_name='bonafiderequest',
            index=models.Index(fields=['student', 'status', 'requested_at'], name='bonafide_student_status_idx'),
        ),
        migrations.AddIndex(
            model_name='bonafiderequest',
            index=models.Index(fields=['status', 'requested_at'], name='bonafide_status_requested_idx'),
        ),
        migrations.AddIndex(
            model_name='branchchangerequest',
            index=models.Index(fields=['student', 'status'], name='branch_student_status_idx'),
        ),
        migrations.AddIndex(
            model_name='leave',
            index=models.Index(fields=['user', 'status', 'date_from', 'date_to'], name='leave_user_status_dates_idx'),
        ),
        migrations.AddIndex(
            model_name='leave',
            index=models.Index(fields=['status', 'created_at'], name='leave_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='noduesentry',
            index=models.Index(fields=['student', 'category', 'is_cleared'], name='no_dues_student_category_idx'),
        ),
        migrations.AddIndex(
            model_name='noduesrequest',
            index=models.Index(fields=['student', 'status', 'requested_at'], name='no_dues_student_status_idx'),
        ),
        migrations.AddIndex(
            model_name='noduesrequest',
            index=models.Index(fields=['status', 'requested_at'], name='no_dues_status_requested_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'unread', 'deleted', 'timestamp'], name='notification_user_state_idx'),
        ),
        migrations.AddIndex(
            model_name='seminar',
            index=models.Index(fields=['student', 'status', 'created_at'], name='seminar_student_status_idx'),
        ),
        migrations.AddIndex(
            model_name='seminar',
            index=models.Index(fields=['status', 'scheduled_start', 'scheduled_end'], name='seminar_status_slot_idx'),
        ),
        migrations.AddIndex(
            model_name='supervisorassignment',
            index=models.Index(fields=['student', 'is_primary', 'is_active'], name='supervisor_student_active_idx'),
        ),
        migrations.AddIndex(
            model_name='supervisorassignment',
            index=models.Index(fields=['supervisor', 'is_primary', 'is_active'], name='supervisor_load_idx'),
        ),
        migrations.AddIndex(
            model_name='taassignment',
            index=models.Index(fields=['student', 'status', 'start_date', 'end_date'], name='ta_student_status_dates_idx'),
        ),
        migrations.AddIndex(
            model_name='taassignment',
            index=models.Index(fields=['course', 'status'], name='ta_course_status_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowauditlog',
            index=models.Index(fields=['entity_type', 'entity_id', 'created_at'], name='audit_entity_created_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowauditlog',
            index=models.Index(fields=['actor', 'created_at'], name='audit_actor_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='assistantshipclaim',
            constraint=models.CheckConstraint(condition=models.Q(('date_to__gte', models.F('date_from'))), name='assistantship_date_to_on_or_after_date_from'),
        ),
        migrations.AddConstraint(
            model_name='branchchangerequest',
            constraint=models.CheckConstraint(condition=models.Q(('current_branch', models.F('requested_branch')), _negated=True), name='branch_change_requested_branch_differs'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(condition=models.Q(('credits__gt', 0)), name='course_credits_positive'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gt', 0)), name='course_capacity_positive'),
        ),
        migrations.AddConstraint(
            model_name='leave',
            constraint=models.CheckConstraint(condition=models.Q(('date_to__gte', models.F('date_from'))), name='leave_date_to_on_or_after_date_from'),
        ),
        migrations.AddConstraint(
            model_name='noduesentry',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='no_dues_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='supervisorassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_primary', True)), fields=('student',), name='one_active_primary_supervisor_per_student'),
        ),
        migrations.AddConstraint(
            model_name='taassignment',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='ta_assignment_end_on_or_after_start'),
        ),
    ]
